### PR TITLE
Hyrax 257

### PR DESCRIPTION
**Pull request by vskorole**

### CODE REVIEW

**Comment by jgallagher59701** [comment]
Demo looks good - I think this is ready for a merge.

**Comment by jgallagher59701** [comment]
Nathan, do you concur?

**Comment by vskorole** [comment]
I don't know how but this already works in UAT. You can look at this in cloudtamer:
https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/hyrax-uat/log-events/uat$252Fhyrax-container$252F521aaf41-7b9d-4371-8700-8d1600751880
I don't like that every line of log events is expanded as one line of json. I think every line should expands as whole json.

**Comment by ndp-opendap** [comment]
These production rules for TravisCI are broken. 
This should NOT be building an pushing to docker hub for a PR.
We need to understand why this is happening.

**Comment by ndp-opendap** [comment]
TravisCI rules fixed.

**Pull request merged**
