### PR TITLE
Install awscli using python3 so it works!

### PR DESCRIPTION
**Pull request by jgallagher59701**
Modified the way awscli is installed so it uses Python3

### CODE REVIEW

**Comment by ndp-opendap** [comment]
Before we merge this we need ti make sure these changes are made in the corresponding template/hyrax, template/besd, and template/ngap files. Otherwise they won't be reflected in our official release images.

**Comment by jgallagher59701** [comment]
OK. I did not make the change to the ngap code - I only changes the Dockerfile files in hyrax and besd, if there's a 'template' file in there, I didn't touch it. I'll look at this ASAP - which will probably be this afternoon.

**Comment by jgallagher59701** [comment]
Ah, I see you edited the ngap Docker file and also removed the part where the AWS key info was echoed. Is this good to go?

**Comment by ndp-opendap** [comment]
No! The templates need to be edited to match.

`hyrax-docker/template/(bes|hyrax|ngap)` all need to receive these changes

**Comment by jgallagher59701** [comment]
OK. I'll look into that.

**Comment by jgallagher59701** [comment]
I think it's done - all six of the Dockerfiles (template/{hyrax,besd,ngap} and hyrax-builds/{hyrax,besd,ngap}) use python3 to install the aws cli and that caused the aws tool to use python3 which it needs. I tested this with the 'hyrax' Docker build only, so there may be some issues still to be resolved.

**Comment by jgallagher59701** [comment]
Hmmm.... I wonder if this is happening because I user 'set -e' with the yum install and python3 -m pip install commands.

**Review by ndp-opendap — APPROVED** [review]
I reviewed the changes in `hyrax-builds` and in `templates` and made a number of adjustments - it looked like some of the files in `templates` were out-of-date w.r.t. the more recent changes in our `hyrax-builds` collection which is where most/all of our evolutionary changes are being made. I think it's time to examine the (modestly) different way that the templates files are used/structured with an eye to rewriting the the `mkDist` script so that we might build the official release images using the `hyrax-builds` Docker assets, the primary motivation being to have a single source of truth for our Docker images.

**Comment by jgallagher59701** [comment]
Yeah, I agree. What I found was that I was duplicating all my changes in 'hyrax-builds' and 'template' and was wondering why we not just using one. So, make a ticket for that refactor and see how it fits into the flow of things.

**Comment by ndp-opendap** [comment]
We have the `hyrax-builds` and `templates` because that happened over time. The `templates` machinery pulls RPMs and signatures from www.opendap.org and uses the signatures while building the Docker image.

The `hyrax-builds` machinery builds the images by pull RPMs from our S3 bucket (not signatures)

**Comment by jgallagher59701** [comment]
So how should we move forward with the PR?

**Comment by ndp-opendap** [comment]
It's time to merge these changes. [HYRAX-748](https://bugs.earthdata.nasa.gov/browse/HYRAX-748) captures the refactoring for a single source of Dockerfile truth and I think this is good to go for now.

**Comment by jgallagher59701** [comment]
I'll merge this and hopefully start on the RHEL8 container ASAP

**Pull request merged**
